### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'ifmap_server_ip'

### ISSUE THREAD

**Issue by alexanderheckel** [Juniper/contrail-ansible-deployer#20]
config/instances.yaml
```
provider_config:
  bms:
    ssh_pwd: contrail123
    ssh_user: root
    domainsuffix: local
    ntpserver: de.pool.ntp.org
instances:
  bms1:
    provider: bms
    ip: 10.10.10.11
    roles:
      openstack:
      config_database:
      config:
      control:
      analytics_database:
      analytics:
      webui:
  bms2:
    provider: bms
    ip: 10.10.10.12
    roles:
      openstack_compute:
      vrouter:
        VROUTER_GATEWAY: 10.10.10.1
  bms3:
    provider: bms
    ip: 10.10.10.13
    roles:
      openstack_compute:
      vrouter:
        VROUTER_GATEWAY: 10.10.10.1
contrail_configuration:
  RABBITMQ_NODE_PORT: 5673
  KEYSTONE_AUTH_URL_VERSION: /v3
  AUTH_MODE: keystone
kolla_config:
  customize:
    nova.conf: |
      [libvirt]
      virt_type=qemu
      cpu_mode=none
  kolla_globals:
    kolla_internal_vip_address: 10.10.10.11
    kolla_external_vip_address: 10.10.10.11
    enable_haproxy: "no"
    enable_ironic: "no"
    enable_swift: "no"
```

Docker Repository and Version: opencontrailnightly / master-115

Issue:

```
[root@controller-1 /]# service-instance list
Traceback (most recent call last):
  File "/usr/bin/service-instance", line 253, in <module>
    main()
  File "/usr/bin/service-instance", line 248, in main
    si = ServiceInstanceCmd(args_str)
  File "/usr/bin/service-instance", line 52, in __init__
    self._novaclient_init()
  File "/usr/bin/service-instance", line 145, in _novaclient_init
    auth_url='http://' + self._args.ifmap_server_ip + ':5000/v2.0')
AttributeError: 'Namespace' object has no attribute 'ifmap_server_ip'
```

**Comment by alexanderheckel** [comment]
Feel free to leave a comment if this is the wrong repository to report the issue - thanks.

**Comment by Andrey-mp** [comment]
Hi,
better place for bug is LP - https://bugs.launchpad.net/juniperopenstack/?orderby=-id&start=0
it's project unrelated and at least it's managed by the team.

about service-instance utility itself - looks like it's broken since it was created.
did it work for you in R4.x or in R3.x?

**Comment by alexanderheckel** [comment]
Hi, thanks for you quick reply.
Moved to https://bugs.launchpad.net/juniperopenstack/+bug/1773577
